/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as AchievementsRouteImport } from './app/achievements'
import { Route as AdminsRouteImport } from './app/admins'
import { Route as LoginRouteImport } from './app/login'
import { Route as ReviewsRouteImport } from './app/reviews'
import { Route as SettingsRouteImport } from './app/settings'
import { Route as TrainingsIndexRouteImport } from './app/trainings/index'
import { Route as TrainingsIdRouteImport } from './app/trainings/$id'
import { Route as UsersIndexRouteImport } from './app/users/index'
import { Route as UsersIdRouteImport } from './app/users/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsRoute = AdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingsIndexRoute = TrainingsIndexRouteImport.update({
  id: '/trainings/',
  path: '/trainings/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingsIdRoute = TrainingsIdRouteImport.update({
  id: '/trainings/$id',
  path: '/trainings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admins': typeof AdminsRoute
  '/login': typeof LoginRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/trainings/$id': typeof TrainingsIdRoute
  '/users/$id': typeof UsersIdRoute
  '/trainings/': typeof TrainingsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admins': typeof AdminsRoute
  '/login': typeof LoginRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/trainings/$id': typeof TrainingsIdRoute
  '/users/$id': typeof UsersIdRoute
  '/trainings': typeof TrainingsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admins': typeof AdminsRoute
  '/login': typeof LoginRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/trainings/$id': typeof TrainingsIdRoute
  '/users/$id': typeof UsersIdRoute
  '/trainings/': typeof TrainingsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/admins'
    | '/login'
    | '/reviews'
    | '/settings'
    | '/trainings/$id'
    | '/users/$id'
    | '/trainings/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/admins'
    | '/login'
    | '/reviews'
    | '/settings'
    | '/trainings/$id'
    | '/users/$id'
    | '/trainings'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/admins'
    | '/login'
    | '/reviews'
    | '/settings'
    | '/trainings/$id'
    | '/users/$id'
    | '/trainings/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminsRoute: typeof AdminsRoute
  LoginRoute: typeof LoginRoute
  ReviewsRoute: typeof ReviewsRoute
  SettingsRoute: typeof SettingsRoute
  TrainingsIdRoute: typeof TrainingsIdRoute
  UsersIdRoute: typeof UsersIdRoute
  TrainingsIndexRoute: typeof TrainingsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins': {
      id: '/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainings/': {
      id: '/trainings/'
      path: '/trainings'
      fullPath: '/trainings/'
      preLoaderRoute: typeof TrainingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainings/$id': {
      id: '/trainings/$id'
      path: '/trainings/$id'
      fullPath: '/trainings/$id'
      preLoaderRoute: typeof TrainingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AdminsRoute: AdminsRoute,
  LoginRoute: LoginRoute,
  ReviewsRoute: ReviewsRoute,
  SettingsRoute: SettingsRoute,
  TrainingsIdRoute: TrainingsIdRoute,
  UsersIdRoute: UsersIdRoute,
  TrainingsIndexRoute: TrainingsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
